hindi=int(input('enter the number'))
print(hindi)
maths=int(input('enter the number'))
print(maths)
science=int(input('enter the number'))
print(science)
english=int(input('enter the number'))
print(english)
computer=int(input('enter the number'))
print(computer)
